### ISSUE TITLE
Устанавливать pkcs11 лучше в начале из официального репозитория. и только в случае провала идти к Рутокен 

### ISSUE THREAD

**Issue by Neraverin** [lo1ol/AstraTokenLoginSetupper#2]
https://github.com/lo1ol/AstraTokenLoginSetupper/blob/fb8a14e428bdb60cc2759274a1308d77f6290294/setup.sh#L15

**Comment by lo1ol** [comment]
Не думал, что он етсь в официальном репозитории. Думаю для астры можно оставить только закачку из официального репозитория

**Comment by lo1ol** [comment]
https://github.com/lo1ol/AstraTokenLoginSetupper/commit/f8cdb9cd8f34e6bc37cde1ca5d470d1a8b38c584
