### ISSUE TITLE
Ничего не написали и вышли с мусоров cert_id в следующую функцию

### ISSUE THREAD

**Issue by Neraverin** [lo1ol/AstraTokenLoginSetupper#5]
https://github.com/lo1ol/AstraTokenLoginSetupper/blob/fb8a14e428bdb60cc2759274a1308d77f6290294/setup.sh#L37

**Comment by Neraverin** [comment]
Если не ошибаюсь, то bash не гарантирует, что там не будет числа

**Comment by lo1ol** [comment]
https://github.com/lo1ol/AstraTokenLoginSetupper/commit/f8cdb9cd8f34e6bc37cde1ca5d470d1a8b38c584
