### ISSUE TITLE
Зачем пользователю придумывать число, для его есть генератор? И тем более проверять не ошибется ли он.

### ISSUE THREAD

**Issue by Neraverin** [lo1ol/AstraTokenLoginSetupper#7]
https://github.com/lo1ol/AstraTokenLoginSetupper/blob/fb8a14e428bdb60cc2759274a1308d77f6290294/setup.sh#L50

**Comment by lo1ol** [comment]
https://github.com/lo1ol/AstraTokenLoginSetupper/commit/f8cdb9cd8f34e6bc37cde1ca5d470d1a8b38c584
